# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.



paths:
    - .

files:
    js:
        extensions:
            - .js
        template: |
            /* This Source Code Form is subject to the terms of the Mozilla Public
             * License, v. 2.0. If a copy of the MPL was not distributed with this
             * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
    html:
        extensions:
            - .html
            - .vue
        template: |
            <!-- This Source Code Form is subject to the terms of the Mozilla Public
                 License, v. 2.0. If a copy of the MPL was not distributed with this
                 file, You can obtain one at https://mozilla.org/MPL/2.0/. -->
    py:
        extensions:
            - .py
        skip_shebang: true
        template: |
            # This Source Code Form is subject to the terms of the Mozilla Public
            # License, v. 2.0. If a copy of the MPL was not distributed with this
            # file, You can obtain one at https://mozilla.org/MPL/2.0/.

    yaml:
        extensions:
            - .yaml
        template: |
            # This Source Code Form is subject to the terms of the Mozilla Public
            # License, v. 2.0. If a copy of the MPL was not distributed with this
            # file, You can obtain one at https://mozilla.org/MPL/2.0/.
